In [27]:
# as clause
import numpy as np

In [28]:
A = np.matrix("2,1,2;1,0,1;3,1,3")

In [29]:
B = np.matrix("2;3;-1")

In [30]:
print(A)

[[2 1 2]
 [1 0 1]
 [3 1 3]]


In [31]:
print (B)

[[ 2]
 [ 3]
 [-1]]


In [ ]:
#Find the determinant

In [33]:
# data given in matrix format (text set) 
det_A = np.linalg.det(A)

In [34]:
print(det_A)

1.665334536937729e-16


In [35]:
det_B = np.linalg.det(B)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
# camel, snake, pascal